source "https://rubygems.org"

gem "rails", "~> 7.2.3"
gem "sprockets-rails"

gem "pg"
gem "sqlite3", ">= 1.4", group: [:development, :test]

gem "puma", ">= 5.0"

gem "jsbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "cssbundling-rails"
gem "jbuilder"

gem "devise"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"
gem "pundit"

gem "inertia_rails"

gem "pagy"

gem "prawn"
gem "prawn-table"

gem "image_processing", "~> 1.2"
gem "cloudinary"

gem "dotenv-rails", groups: [:development, :test]

gem "httparty"

gem "sentry-ruby"
gem "sentry-rails"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem "web-console"
  gem "letter_opener"
end
